### ISSUE TITLE
NMF module annotation

### ISSUE THREAD

**Issue by Li-ZhiD** [fungenomics/HGG-oncohistones#1]
Nice works!
I have a question that how to access the data mentioned in NMF module annotation code, "readRDS(here("data/scRNAseq/references/mouse_atlas_extended/joint_mouse_extended.signatures_ID_20201028.Rds"))".
Thanks!

**Comment by sjessa** [comment]
Hi @Li-ZhiD,

Apologies that I didn't see this question earlier! I haven't uploaded all the intermediate files used in the analysis, but I can share how the object is formatted and how to create it:

The R object loaded is a list of four elements, named `hg_sym`, `hg_ens`, `mm_sym`, `mm_ens`. Each element contains a list of cluster-specific gene signatures from the mouse atlases referenced in the paper. The four elements contain the same gene signatures, but they are in the form of human gene symbols, human ENSEMBL IDs, mouse gene symbols, or mouse ENSEMBL IDs, respectively.

It would look something like this:

```r
> str(x)
List of 4
 $ hg_sym:List of 290
  ..$ F-e10_CEXN1     : chr [1:96] "TBR1" "SAMD3" "LHX9" "NHLH2" ...
  ..$ F-e10_CHEM      : chr [1:95] "RSPO3" "RSPO2" "WNT8B" "WLS" ...
 $ mm_sym:List of 290
  ..$ F-e10_CEXN1     : chr [1:100] "Tbr1" "Samd3" "Lhx9" "Nhlh2" ...
  ..$ F-e10_CHEM      : chr [1:98] "Rspo3" "Rspo2" "Wnt8b" "Wls" ...
 $ hg_ens:List of 290
  ..$ F-e10_CEXN1     : chr [1:96] "ENSG00000136535" "ENSG00000164483" "ENSG00000143355" "ENSG00000177551" ...
  ..$ F-e10_CHEM      : chr [1:95] "ENSG00000146374" "ENSG00000147655" "ENSG00000075290" "ENSG00000116729" ...
 $ mm_ens:List of 290
  ..$ F-e10_CEXN1     : chr [1:99] "ENSMUSG00000035033" "ENSMUSG00000051354" "ENSMUSG00000019230" "ENSMUSG00000048540" ...
  ..$ F-e10_CHEM      : chr [1:97] "ENSMUSG00000019880" "ENSMUSG00000051920" "ENSMUSG00000036961" "ENSMUSG00000028173" ...

```

You could construct this by taking the last four columns of Supplementary Table 7, which provides these genes, and then use the column "Label_20201028" for names of the elements.

**Comment by Li-ZhiD** [comment]
Thank you!
