### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by yilevine** [fungenomics/HGG-oncohistones#2]
Hi,

Really nice work and thanks for sharing the code!
I was just going through the _preprocessing_scMultiome.Rmd_ in R-4 folder.
But I found some files are missing.  
One is **CellCycleGeneList_1134_whitfield_2002_mice_gene_symbols.txt**
And other one is **data/scATACseq/references/promoter_coordinates.Rda** in config file. 
I was wondering if you could share or upload these two data?
Thanks!

Best,
YIle

**Comment by sjessa** [comment]
Hi, thanks for the kind words and for checking out the code!

Thanks for catching that. The first file you mentioned was located outside this directory, but I have added a copy to this repo. You can now find the folder which is referenced as `SEURAT_V3_ASSETS` or `file.path(params$assets, "resources")` in the various `preprocessing_*.Rmd` scripts here: https://github.com/fungenomics/HGG-oncohistones/tree/master/code/seurat_v3_resources, and that contains `CellCycleGeneList_1134_whitfield_2002_mice_gene_symbols.txt`.

For the second, the script to produce that file is here: https://github.com/fungenomics/HGG-oncohistones/blob/master/code/scripts/make_scATAC_refs.R. It essentially follows directions in the Signac package.

Selin

**Comment by yilevine** [comment]
Hi Selin,

Really thanks for the reply and for sharing the code and the data.
I also would like to know how you integrated multiuome data (RNA + ATAC) across samples. I didn't find the related codes. 
Could you also share it?
If I missed it, could you tell me where I can find it in this repo?
Thanks!

Best,
Yile

**Comment by sjessa** [comment]
Hi Yile,

The integration script for harmony is at [`code/scripts/integrate_harmony.R`](https://github.com/fungenomics/HGG-oncohistones/blob/3b97c31859518ea40f2ed73101279dd2f59052b3/code/scripts/integrate_harmony.R).
I've added some more details in this section: https://github.com/fungenomics/HGG-oncohistones/blob/master/README.md#data-integration

Selin

**Comment by yilevine** [comment]
Hi Selin,

Thanks a lot! I will have a look.

Yile
